language: objective-c
os: osx
osx_image: xcode9
env:
  global:
    - FRAMEWORK_NAME=CatCrypto
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script: xcodebuild clean build -sdk iphonesimulator -workspace CatCrypto.xcworkspace -scheme CatCrypto CODE_SIGNING_REQUIRED=NO
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: o6RmYXVRwgS1OZ8hxYXvHILb6FanDqMZiWb6o76R8thhBTULyJnUcm9paa1UR7JvZqb8atxfpYmpxA3/ISlLU2D4ENqJz8FqWX3L6n9IQCVqGR3pQk7AgSl3lYC97PJr64gvkRNfcKtF4Mk4QG5YeEm3PnEbkv1tJmgUSlqHa5QwHqDsj6zxaYRO142EHgC0qzp8EC8Cnfl5gvBV2hYe1aYtRISI9y9IJGVNFkIRelV+Bd41wFDLyDPnF+kyEAW0eSOhLT8ZpgB/DfVn5ailUmk11WrgW5NIFshjhf9i+TH/jhmUiG9rgU1JGi2dXGOcRJVd8dMRoUJWetFfGYdEtW+UbUtOEy/7Zv4YbNCziMlgmWB9DvvcJCLYzLcW2uS87hvBhcCWw5cVvYe5rhtbVSxo28lQdGCTJmI4s+lsuNUP4fEQ0uMdn5rYhHSeeVCyltkoxCjti8ZhxXnT0FVuKimYoQUtjgUEOVur4Nh442JW4BKJ2ud3aT4MoqpYSBciyP9ETDb7ImPxhX8EjdQ43kjZYsBVvyQqx8HXvnOTa9RfGri0L5kkXpa6yD3rkAVgSZUl4oVrRWZTog4zWJND/jigPzxHXa4HXpXlqyjHHIPyjHH1ltufnUJmpWqvVNU5iHeeqm1e/gFU9x9wOfcx1il7Z75LJofbIPR0dW22Ji4=
  file: CatCrypto.framework.zip
  skip_cleanup: true
on:
  repo: ImKcat/CatCrypto
  tags: false