language: objective-c
os: osx
osx_image: xcode9
env:
  global:
    - FRAMEWORK_NAME=CatCrypto
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script: xcodebuild clean build -sdk iphonesimulator -workspace CatCrypto.xcworkspace -scheme CatCrypto CODE_SIGNING_REQUIRED=NO
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: "SxQbmS7R8kfnRfKt67qhFqhra1vbOShtSggcrC0VWaLUNCw3SZN2HBlOii3+mFlKrPZWbJUZLXzoeXJ3l2rhtU3cGddMeETmcykhNzCExNGf5mFphSw+Go6tdc5pyyVo9qofaKWhEk+dlZ0eM5BzxDToTIIFNHgZwp0NHgoGKvm2tlliIJNAza6LElgTZDRE9M6K03KIb0ySmjIf16/xLl5d/6hDMpbMQJCIOAHp1y2dclaKPeO6aFqKTMSsagG8wnUWCqzwNNFAlV9xYUg6zcuThhI4dS5WKvY/ip2ZP7wwWdngTgBZs3Hk9TtWfmXHHBHlV3t00oolPmNE8KPb5PFIPyi3plK8ftzzzgZq00vadR2AzFViadNDv9sJOKyvdtMRP2E24zEcUw91rMD2zE8FxQpws/+/5KwCOyCiVpG8to3/CxTGDb5hiVP0IUNLOeIdxnkm1Pbt4tIsob6W89JKVxMcgytEsGbrKXyaJ0PKSvrkrskb2xuoTQhUwJeWYf6YkpevX3pHY9rhfZaT1aXp0k++KD8Pxderpt2wO+5F3IAPIaavWszXzNyn+AR1NuaNsL9q2YqnkBAeeXJ2N4geZoyD3FYkvBp61d22ruPA9fW1zF8ul3dz/taOe5/qd5UpIlUZn3yCJlnjnu8YsQWnrHYbaRL5gSgRN1gvrRo="
  file: CatCrypto.framework.zip
  skip_cleanup: true
on:
  repo: ImKcat/CatCrypto
  tags: true